### ISSUE TITLE
Permission location problem

### ISSUE THREAD

**Issue by Shukkk** [Plotprojects/plot-flutter#1]
Hai,

file plotconfig.json:
"automaticallyAskLocationPermission": true,

im using this command, and after install the app ask for permission, then i allow. but when i scroll down notification bar, i noticed that my location icon not enable. that is my problem, please help me. thank you

**Comment by marshall20** [comment]
Hi, it requests permission on the app level, if the phone's location was switched off by the user, it will continue off, and only the user can manually turn it back on.

**Comment by Shukkk** [comment]
okay, now i get it, thank you sir.
